axelarnetwork/axelarjs-sdk

README.md
Any further clarification needed?
=> chore: restore README code snippets

src/libs/TransferAssetBridge.ts, src/libs/types/index.ts, test/e2e/app.e2e-spec.ts, test/e2e/data/index.ts, test/e2e/parts/03.deposit-address.spec.ts
Added get deposit address wrapper function.
TODO: add metamask signing option
=> chore: add getDepositAddress wrapper

src/libs/AxelarGateway.ts, src/libs/abi/axelarGatewayAbi.json, src/libs/test/axelarGateway.spec.ts, src/libs/types/index.ts
- Update the abi
- Change some params name
=> Update abi and arg name

src/libs/GatewayTx.ts
=> Fix missing provider

package-lock.json, package.json, src/assets/index.ts
=> Version0.4.31

dependabot.yml, package-lock.json, package.json
clean up dev dependencies and bump version
=> Dependencies

src/services/RestService.ts, src/services/test/RestService.spec.ts
=> chore: fixing reported bug in err.json

src/libs/AxelarQueryAPI.ts, src/libs/test/AxelarQueryAPI.spec.ts
`getAssetConfigFromDenom` will improve how we get the asset information easier
=> feat(AxelarQueryAPI): add getAssetConfigFromDenom

src/libs/AxelarAssetTransfer.ts, src/libs/AxelarQueryAPI.ts, src/libs/TransactionRecoveryApi/AxelarDepositRecoveryAPI.ts, src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts, src/libs/TransactionRecoveryApi/client/EVMClient/index.ts, src/libs/TransactionRecoveryApi/helpers/contractEventHelper.ts, src/libs/test/TransactionRecoveryAPI/helper/contractEventHelper.spec.ts, src/services/SocketService.ts, src/utils/asyncRetry.ts
Fix #194 
Tests have now covered the issue:
=> Fix nativeAddGas api doesn't detect gas unpaid correctly

CHANGELOG.md
adding changelog entries for 0.12.0
=> feat: adding 0.12.0 changelogs

src/libs/AxelarAssetTransfer.ts, src/libs/AxelarQueryAPI.ts
adding some small syntactical fixes to method signatures
=> Small fixes

CHANGELOG.md, package-lock.json, package.json
This release will include the following PRs:
- https://github.com/axelarnetwork/axelarjs-sdk/pull/236
- https://github.com/axelarnetwork/axelarjs-sdk/pull/233
=> Release 0.12.4

src/libs/AxelarQueryAPI.ts, src/libs/test/AxelarQueryAPI.spec.ts, src/libs/test/stubs/index.ts, src/libs/types/index.ts
```bash
yarn test -t "minGasPrice" AxelarQueryAPI.spec.ts
```
=> chore: fix wrong min_gas_price calculation

src/libs/AxelarQueryAPI.ts
fix express fee underflow issue
=> fix: estimate gas fee underflow issue

package.json, pnpm-lock.yaml, scripts/postinstall.js, src/libs/AxelarQueryAPI.ts
=> feat: implement npm update checker

package.json, pnpm-lock.yaml, scripts/postinstall.js
=> feat: dynamic renderBox + package manager specific instructions

.github/workflows/release.yml, package.json
bump version to 0.13.4 and update release action to trigger after created a release on gh
=> chore: update release action

CHANGELOG.md, package.json, src/chains/supported-chains-list.ts, src/libs/AxelarGateway.ts, src/libs/TransactionRecoveryApi/constants/chain/mainnet.ts, src/libs/TransactionRecoveryApi/constants/chain/testnet.ts
- Add `Immutable` to mainnet configs; update `Immutable` testnet RPC
=> Version0.13.8

src/libs/TransactionRecoveryApi/constants/chain/mainnet.ts
Update the rpc endpoint for filecoin mainnet
=> chore: update filecoin rpc endpoint

package.json
Preparing 0.17.2 release by publishing alpha version for testing first
=> release: 0.17.2

package.json, pnpm-lock.yaml, src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts, src/libs/TransactionRecoveryApi/helpers/xrplHelper.ts, src/libs/test/AxelarQueryAPI.spec.ts, src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
https://axelarnetwork.atlassian.net/browse/AXE-9229
https://axelarnetwork.atlassian.net/browse/AXE-8352
- Added `addGasToXrplChain` function to the SDK 
- Supported mainnet for `addGasToStellar` function
=> feat: add gas for xrpl

package.json, src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
This PR changed chain config look up source from the `env-chain-config` file (e.g. [testnet-chain-config](https://axelar-testnet.s3.us-east-2.amazonaws.com/testnet-chain-config.json)) to the `env-chain-config-1.x` (e.g. [testnet-config-1.x](https://axelar-testnet.s3.us-east-2.amazonaws.com/configs/testnet-config-1.x.json)) file instead since it's more up-to-date.
=> chore: fix chain not found in add native gas

package.json
=> release: 0.17.5

package.json
=> chore: bump version to 0.17.7

src/chains/supported-chains-list.ts
Add agoric testnet.
Example usage:
```js
const axelarQueryApi = new AxelarQueryAPI({
environment: Environment.TESTNET,
});
const response = await axelarQueryApi.estimateGasFee(
CHAINS.TESTNET.AGORIC,
EvmChain.SEPOLIA,
800_000n
);
```
=> chore: add agoric testnet
