src/assets/devnet.assets.ts
src/assets/index.ts
src/constants/index.ts
src/libs/AxelarGateway.ts
src/libs/types/index.ts

This PR:
* adds devnet assets
* updates gateway contract addresses for devnet3 to AxelarGateway
* updates environment configs for devnet3 for ethersjs providers
once merged, we should:
* deploy v0.5.0-alpha.4 as latest alpha version
* make sure devnet works. one way to test is to download the new examples app: https://github.com/axelarnetwork/sdk-demo-v5-deposit-address and change the environment on this line: https://github.com/axelarnetwork/sdk-demo-v5-deposit-address/blob/main/src/App.tsx#L10 and see if we get a deposit address in the app.

Devnet assets

---

src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/TransactionRecoveryApi/constants/error.ts
src/libs/TransactionRecoveryApi/helpers/contractCallHelper.ts
src/libs/TransactionRecoveryApi/helpers/index.ts
src/libs/TransactionRecoveryApi/index.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/AxelarRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/helper/contractCallHelper.spec.ts
src/libs/test/stubs/index.ts
src/libs/types/index.ts

Add `execute` function with tests.
Note: the base branch is `feat/addGas` for now, once https://github.com/axelarnetwork/axelarjs-sdk/pull/98 is merged, i will rebase to new alpha version branch.
`yarn test -t "callContract" contractCallHelper.spec.ts`
`yarn test -t "execute" AxelarGMPRecoveryAPI.spec.ts`
TODO:

Refactor `execute` function

---

src/assets/testnet.assets.ts
src/chains/Aurora/index.ts
src/chains/index.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/TransactionRecoveryApi/index.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/AxelarRecoveryAPI.spec.ts

user reported a small issue where txStatus returns "approved" instead of "executed" even tho the tx was executed. 
in the original implementation, `https://testnet.api.gmp.axelarscan.io/` used to return an `is_executed` property that was used to check if the tx was executed, but now that the `is_executed` property is gone, it will never show a tx as being executed.  
given that change, this small fix reads the `status` property instead. 
cc @pjenviri @npty

chore: fixing small bug in queryTransactionStatus

---

.github/workflows/release.yml

After enabled branch protection rule, the automate bump version gh action won't be able to push to main branch anymore.
Change the default `GITHUB_TOKEN` to my personal access token, should allow it to be able to push again.
Here's all the permission this token has:

Change GITHUB_TOKEN

---

package.json

files to exclude to optimize bundle size. closes #116

chore: files to exclude to optimize bundle size

---

src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts

This PR minimizes the lengthy testing time in `AxelarGMPRecoveryAPI` by mocking the API calls.
As a result of the optimization, the testing time in `AxelarGMPRecoveryAPI` is decreased from `3m 54s` to `31s`.
Testing on Macbook M1.
| Before                                                                                                          	| After                                                                                                           	|
|-----------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------	|
| ![image](https://user-images.githubusercontent.com/78221556/188408733-9d35ebee-32b1-4205-9930-75bbd2d36 …

Optimize testing time for 'AxelarGMPRecoverAPI'

---

CHANGELOG.md
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/test/TransactionRecoveryAPI/AxelarRecoveryAPI.spec.ts
src/services/RestService.ts
src/services/SocketService.ts
src/services/test/RestService.spec.ts
test/integration/app.integration-spec.ts
test/integration/parts/00.deposit-address-single.spec.ts
test/integration/parts/01.deposit-address.spec.ts

* update queryTransactionStatus in AxelarRecoveryApi to include new executing status.
* update GET requests in AxelarRecoveryApi to disable cache.
* fixed a regression issue caused in 0.11.0 in AxelarAssetTransfer, where the getDepositAddress method is no longer able to generate deposit addresses for cosmos-based destination chains, e.g. Axelar, Osmosis. Please update to this version if you are using this method.
* [technical fix]: improving error messaging of REST responses.

chore: adding changelog

---

CHANGELOG.md
src/libs/AxelarAssetTransfer.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarDepositRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/test/AxelarAssetTransfer.spec.ts
src/libs/test/AxelarQueryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/stubs/index.ts
src/libs/types/index.ts
src/utils/validateChain.ts

Closes #163 
Adds the following public functions:
- `getActiveChains(): Promise<string[]>` returns a list of active chains
- `isChainActive(chainId: string)`: Check if a chain is active.
- `throwIfInactiveChain(chainId: string)`: Throw an error if a chain is inactive. (for internal use purposes)
The `throwIfInactiveChain` check is added to the very beginning of the following apis:
- getDepositAddressForNativeWrap
- getDepositAddressForNativeUnwrap
- getDepositAddressFromRemote
- validateOfflineDepositAddress
- getInitRoomId
- getNativeGasBaseFee
- estimateGasFee
- calculateNativeGasFee
- calculateGasFee
- Change the function name from `isValidChainIdentifier` to `throwIfInvalidChainId`

Implement getActiveChains query and more

---

src/libs/AxelarAssetTransfer.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/test/AxelarAssetTransfer.spec.ts
src/libs/test/AxelarQueryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts

Closes #216 
- Removed `getGasReceiverContractAddress` and `getDepositServiceContractAddress` functions in `AxelarAssetTransfer` and a duplicated function.
- Added more flexible `getContractAddressFromConfig` function in `AxelarQueryAPI`
- Changed the default `refundAddress` to `default_refund_collector`

Change the default refund address

---

CHANGELOG.md
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
test/e2e/testnet/query-transaction-status.e2e-spec.ts

This PR adds `timeSpent` into the `queryTransactionStatus` response.
- `timeSpent` won't always be available. It'll be available at the finalized state e.g. `executed` or `error`
- `timeSpent.total` is not always returned by the `searchGMP` API. So, the SDK calculates it when it doesn't exist, to make sure that it's always presented. (e.g. `0xcbed93b85bac0a04b03722d985197878445492ad29b5deb4472772d706914ca6`)

Add `timeSpent` for `queryTransactionStatus` API

---

CHANGELOG.md
package-lock.json
package.json
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/client/EVMClient/index.ts
src/libs/test/AxelarQueryAPI.spec.ts

adding method to `AxelarQueryAPI` called `getTransferLimit`
* for EVM chains, query directly to the gateway contract for `tokenMintLimit`
* for cosmos chains, query the nexus module
a user would invoke in the following way:
```ts
const config: AxelarQueryAPIConfig = {
environment: Environment.MAINNET,
};
const api = new AxelarQueryAPI(config);
const testEVM = async () => {
const chainId = "ethereum";
const denom = "uusdc";
const res = await api
.getTransferLimit({ chainId, denom })
.catch((e) => console.log(e));
console.log("res", res);
};
const testCosmos = async () => {
const chainId = "osmosis";
const denom = "uusdc";
const res = await api
.getTransferLimit({ chainId, denom })
.catch((e) => console.log(e));
console.log("res", res);
};
testEVM();
testCosmos();
```

feat: adding query for token limit on evm chains

---

package-lock.json
package.json
src/assets/types/index.ts
src/libs/AxelarQueryAPI.ts

* now that we are supporting native assets, users will likely make requests to AxelarQueryApi with assets like "ETH"/"AVAX"/etc.
* this network level query will not work, but the response params will be the same as their corresponding wrapped equivalents, i.e. "weth-wei"/"wavax-wei"/etc. 
* wanted to get your thoughts on the following conversion function in this PR. thoughts?

chore: convert native token to erc in axelar query

---

package-lock.json
package.json
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/helpers/contractCallHelper.ts
src/libs/test/TransactionRecoveryAPI/helper/contractCallHelper.spec.ts
src/libs/types/index.ts

This PR accepts `evmWalletDetails.gasLimitBuffer` for the `execute` function. `gasLimitBuffer` will be added to the gas estimated value before sending `executeWithToken` or `execute` tx. The default value for `gasLimitBuffer` is 0

chore: add `gasLimitBuffer` to execute function

---

CHANGELOG.md
src/constants/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/TransactionRecoveryApi/client/EVMClient/index.ts
src/libs/TransactionRecoveryApi/constants/error.ts
src/libs/TransactionRecoveryApi/helpers/contractEventHelper.ts
src/libs/TransactionRecoveryApi/helpers/getCommandId.ts
src/libs/TransactionRecoveryApi/helpers/index.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts
src/libs/types/index.ts

this PR fixes #175. 
the issue was in the `manualRelayToDestChain` method, which was eagerly attempting to confirm every tx hash without first checking whether the tx has already been confirmed on the network. 
the issue that comes up with `cannot sign command` comes up for transactions that were already confirmed but the batch has not been broadcasted to the destination chain. 
this fix:
* first checks to see whether the transaction was executed/approved/confirmed. 
* if already executed/approved, do nothing
* if already confirmed, attempt to extract the commandId and query the batchedCommandID from the axelarscan API. then check if the commandID in that batched has not been executed, and execute if need be.
* otherwise, do as before.

[work-in-progress] improve manual relay

---

package.json

Hopefully adding a repository link here will get the "repository" link to show up on npm here:  https://www.npmjs.com/package/@axelar-network/axelarjs-sdk/

feat:add repo to package.json for link on npm

---

CHANGELOG.md
src/constants/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/TransactionRecoveryApi/client/EVMClient/index.ts
src/libs/TransactionRecoveryApi/constants/chain/index.ts
src/libs/TransactionRecoveryApi/constants/error.ts
src/libs/TransactionRecoveryApi/helpers/contractEventHelper.ts
src/libs/TransactionRecoveryApi/helpers/getCommandId.ts
src/libs/TransactionRecoveryApi/helpers/index.ts
src/libs/TransactionRecoveryApi/helpers/mappers.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts
src/libs/test/stubs/index.ts
src/libs/types/index.ts

this PR fixes https://github.com/axelarnetwork/axelarjs-sdk/issues/175. it's an update to PR: https://github.com/axelarnetwork/axelarjs-sdk/pull/245 that was accidentally merged
the issue was in the manualRelayToDestChain method, which was eagerly attempting to confirm every tx hash without first checking whether the tx has already been confirmed on the network.
the issue that comes up with cannot sign command comes up for transactions that were already confirmed but the batch has not been broadcasted to the destination chain.
this fix:
* first checks to see whether the transaction was executed/approved/confirmed.
* if already executed/approved, do nothing
* if already confirmed, attempt to extract the commandId and query the batchedCommandID from the axelarscan API. then check if the …

Improve manual relay

---

src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/types/index.ts

two things: 
1. the `addNativeGas` method should accept additional parameters to allow the invoker to specify what gas amount and gas multiple to use
2. the implementation of `addNativeGas`, which calls `subtractGasFee`, should subtract the base fee if the transaction has already been confirmed. (as per #239)

chore: adding a fix to addNativeGasMethod with overestimation

---

CHANGELOG.md
src/libs/AxelarQueryAPI.ts

This PR improves the `estimateGasFee` API to throw an error when an error occurs during an internal function call. Currently, the API returns 0, which makes it difficult for the caller to handle unexpected data.
Previously, if an error occurred during an internal function call, the `estimateGasFee` API would return 0, which could be misinterpreted as a valid gas fee of zero. This PR changes the behavior of the API to throw an error if occurs.
Before this change, if an error occurred during an internal function call, the estimateGasFee API might return:
```
0
```
After this change, the `estimateGasFee` API will throw an error with the message `Failed to estimate gas fee` if it is an unknown error or an error that propagates from the `getNativeGasBaseFee` function.
This change makes it …

chore: throw error instead of returning 0 in estimateGasFee

---

.github/workflows/release-alpha.yml
package.json
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/constants/chain/testnet.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts

Fix the issue with `manualRelayToDestChain` where the web client incorrectly utilizes the provider from the injected browser wallet instead of the rpcUrl embedded in the SDK. This error arises when the injected wallet's network differs from the source chain.

chore: fix manualRelayToDestChain

---

src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/AxelarRecoveryApi.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts

* adding optional parameter to `manualRelayToDestinationChain` method to accept tx log index. builds upon #285

chore: adding optional parameter for log index to recovery methods

---

package.json
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/constants/chain/testnet.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts
src/libs/types/index.ts

1. adding `eventIndex` as an optional parameter to `manualRelayToDestinationChain`
2. using ankr as filecoin testnet rpc

chore: add event index as an optional parameter and fixing filecoin rpc

---

src/libs/AxelarQueryAPI.ts
src/libs/types/index.ts

Removed default value for `gasLimit`. If specified, it should be greater than the minimum value (21k gas).

chore: adjust params

---

.github/workflows/build.yml
CHANGELOG.md
package.json
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts

[0.14.0] - 2024-FEBRUARY-9
Breaking Changes
AxelarQueryAPI: estimateGasFee
gasLimit: Changed from optional (default 700,000) to required.
gasMultiplier: Default changed from 1.1 to auto, using data from [getFees](https://docs.axelarscan.io/interchain/getFees).
AxelarGMPRecoveryAPI
addNativeGas & addGasToCosmosChain: gasLimit is now required, removing the default 700,000.

chore: bump version to 0.14.0

---

CHANGELOG.md
package.json
src/libs/AxelarQueryAPI.ts

[AXE-3183](https://axelarnetwork.atlassian.net/browse/AXE-3183)
This PR ensures that the `gas_execute_multiplier` which returns from the `getFees` API has 2 decimal places at maximum before put into the calculation.
Try calling `estimateGasFee` function given axelar and optimism are source chain and destination chain respectively.
```
Execute Gas Multiplier 1.1550000000000002
Execute Gas Multiplier 1.32
axelarnet to optimism fee: 0.00000000000412665 ETH
optimism to axelarnet fee: 0.01002625182289159 ETH
```
```
Execute Gas Multiplier 1.16
Execute Gas Multiplier 1.32
axelarnet to optimism fee: 0.000000000004133053 ETH
optimism to axelarnet fee: 0.010016512870193104 ETH
```
[AXE-3183]: https://axelarnetwork.atlassian.net/browse/AXE-3183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

chore: ensure 2 decimal places

---

CHANGELOG.md
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/client/EVMClient/index.ts
src/libs/TransactionRecoveryApi/constants/chain/testnet.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts

[AXE-3352](https://axelarnetwork.atlassian.net/browse/AXE-3352?atlOrigin=eyJpIjoiMWU0OGNiN2EzYzUwNDUwYTgxYjJmZGMwZTI2MjE2MWMiLCJwIjoiaiJ9)
This PR updates the `ethereum-2` RPC endpoint and ensures the custom provider is used within `manualRelayToDestChain`
```ts
// Override default rpc endpoint
await api.manualRelayToDestChain(
txHash,
undefined,
undefined,
{
provider: new ethers.providers.JsonRpcProvider(
"https://goerli.gateway.tenderly.co"
),
}
);
```
[AXE-3352]: https://axelarnetwork.atlassian.net/browse/AXE-3352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: custom rpc provider is not used for tx recovery

---

CHANGELOG.md
package.json
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts

[AXE-3351](https://axelarnetwork.atlassian.net/browse/AXE-3351?atlOrigin=eyJpIjoiNjIxZjQ1NTlkMTJlNDIyMDg0NmU1MzQxMzUzNmFiMDYiLCJwIjoiaiJ9)
Added support for cosmos-to-cosmos gmp tx recovery
Example Tx: https://axelarscan.io/gmp/292DF0120C85D85CB90270159FD7CB3C552DA2B076F56577AC5608EA226AF26D
[AXE-3351]: https://axelarnetwork.atlassian.net/browse/AXE-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support cosmos-to-cosmos gmp tx recovery

---

src/libs/fee/getL1Fee.ts

[AXE-3449](https://axelarnetwork.atlassian.net/browse/AXE-3449) 
According to [Mantle V2 Docs](https://docs-v2.mantle.xyz/devs/concepts/tx-fee/ef#example), we can skip L1 fee calculation for Mantle.
Note: currently, the tests are failed because some functions that generated by `axelarjs-types` are not compatible with live `axelar-core`. We have to update `axelarjs-types` first
[AXE-3449]: https://axelarnetwork.atlassian.net/browse/AXE-3449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: return 0 for mantle L1 fee

---

src/constants/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/types/index.ts

**Problem:** Current param types create compatibility conflicts with popular ecosystem libraries such as ethers.js. This can lead to type error issue.
**Solution:** Refactor param types to use string, aligning with standards used by most ecosystem libraries. This improves compatibility and avoids potential workarounds in the future.
[AXE-3533](https://axelarnetwork.atlassian.net/browse/AXE-3533?atlOrigin=eyJpIjoiNzU2MjI3ZjAyY2E1NDVmODg3N2E1ZjZjZjM3ZmJkOTEiLCJwIjoiaiJ9)
[AXE-3533]: https://axelarnetwork.atlassian.net/browse/AXE-3533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: change executeData type from `0x${string}` to `string`

---

src/constants/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/helpers/getCommandId.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/EncodingTests.spec.ts

[AXE-3532](https://axelarnetwork.atlassian.net/browse/AXE-3532)
Fix wrong commandId generation. Note that the `getCommandId` function has a single usage which is used by `evm-to-evm` recovery method.
[AXE-3532]: https://axelarnetwork.atlassian.net/browse/AXE-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: fix commandId generation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
package.json
pnpm-lock.yaml
src/constants/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/types/index.ts

[AXE-3804](https://axelarnetwork.atlassian.net/browse/AXE-3804?atlOrigin=eyJpIjoiYzdkMGI4M2ZjMDY1NDBmMWE1Yjk4OWE3OGFjYTRjMDMiLCJwIjoiaiJ9)
Bump `axelar-cgp-solidity` to `6.3.0 `
[AXE-3804]: https://axelarnetwork.atlassian.net/browse/AXE-3804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump axelar-cgp-solidity to 6.3.0

---

package.json
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts

https://axelarnetwork.atlassian.net/browse/AXE-6051
Fixed the error when trying to add gas for cosmos source chain from the axelarscan ui. 
The sdk expects the `denom` (`usomm`) from the `searchGMP` api in the `gas_paid.returnValues.denom` property, but the api returns ibc asset format instead (`ibc/12A9901F2B585B3563C2AD4919D20ED478CCAB3D7F9ACBB76E829583B99B1DAA`). 
@nrsirapop helps adding a new property called `asset` in the api response, so this pr points to that field instead.

chore: fix wrong denom when adding gas for cosmos source chain

---

CHANGELOG.md
package.json
src/assets/index.ts
src/chains/index.ts
src/chains/types/index.ts
src/libs/AxelarQueryAPI.ts
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts
src/libs/TransactionRecoveryApi/constants/cosmosGasReceiverOptions.ts
src/libs/TransactionRecoveryApi/constants/s3.ts
src/libs/test/AxelarQueryAPI.spec.ts
src/libs/test/stubs/index.ts
src/libs/types/index.ts
src/utils/validateChain.ts
test/e2e/data/index.ts
test/integration/parts/01.deposit-address.spec.ts

feat: update sdk to support Amplifier chains

---

src/constants/index.ts

https://devnet.api.gmp.axelarscan.io/ is returning an error. Not sure if the URL is meant to stay as it is, or needs to change to https://devnet-amplifier.api.axelarscan.io/gmp/, which is the URL that works. 
This is getting in the way of my work, so I had to file a PR. If https://devnet.api.gmp.axelarscan.io/ is meant to be working, could you please recover it asap! and you can close this PR in that case. Thank you.

chore: update devnet GMP API URL

---

src/constants/index.ts

Although the URL for the `devnet` was updated recently, the `devnet-amplifier` one was not.

fix: update devnet-amplifier GMP URL

---

package.json
src/libs/AxelarQueryAPI.ts
src/libs/test/AxelarQueryAPI.spec.ts
src/libs/test/TransactionRecoveryAPI/AxelarGMPRecoveryAPI.spec.ts

https://axelarnetwork.atlassian.net/browse/AXE-9253
Added `estimateITSFee` function.

feat: add estimateITSFee method to AxelarQueryAPI

---

package.json
src/libs/TransactionRecoveryApi/AxelarGMPRecoveryAPI.ts

Removed the transaction status check in the `addNativeGas` function. This addresses an issue with 2-hop transactions where the check incorrectly returns "executed" if the first hop is complete, even if the second hop hasn't been executed yet.

chore: remove check execution

---

src/libs/TransactionRecoveryApi/constants/chain/mainnet.ts

- Fix broken public RPC URLs
- https://rpc.ftm.tools/ has become Freemium, replacing with another URL
- Polygon zkEVM is deprecated, but still updated it in mainnet until it is sunset in 2026

fix(rpc-url): Fix broken RPC URLs in mainnet
